### ISSUE TITLE
Why it can't work when vocab_size=5000?

### ISSUE THREAD

**Issue by fuzihaofzh** [X-czh/SeqGAN-PyTorch#1]
Hi, I'm tryin this code but why it can't work when vocab_size=5000?

**Comment by X-czh** [comment]
Sorry for the late reply, the problem comes with the writing format of the generated toy data.  The generator generates digits as "words" and writes to the file without any deliminator between the digits in the same line. When the vocab_size is larger than 10, a generated "word" can consist of several digits rather than one, e.g. "12". Due to the missing of deliminator, when the program is trying to read from the file, it cannot know where the "word" boundaries are, thus leading to an error. I will soon update the code, adding white spaces as "word" deliminator.
